src/Sly/ContentBundle/Entity/Content.php
<?php

namespace Sly\ContentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="Sly\ContentBundle\Entity\ContentRepository")
 * @ORM\Table(name="content")
 * @ORM\HasLifecycleCallbacks
 */
class Content
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @Assert\Type("boolean")
     * @ORM\Column(type="boolean")
     */
    protected $status;
    /**
     * @ORM\Column(type="string", length=20)
     */
    protected $type;
    /**
     * @Gedmo\Sluggable
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    protected $title;
    /**
     * @Gedmo\Slug(updatable=false, unique=true)
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected $slug;
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $content;
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $excerpt;
    /**
     * @Assert\Url()
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $link;
    /**
     * @Assert\Url()
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    protected $minilink;
    /**
     * @Assert\Type(type="string")
     * @ORM\Column(name="github_file", type="string", length=255, nullable=true)
     */
    protected $githubFile;
    /**
     * @Assert\Type(type="int")
     * @ORM\Column(name="social_network_id", type="bigint", length=20, nullable=true)
     */
    protected $socialNetworkId;
    /**
     * @Assert\File(maxSize="6000000")
     * @ORM\Column(name="picture", type="string", length=255, nullable=true)
     */
    private $picture;
    /**
     * @Assert\DateTime()
     * @ORM\Column(type="datetime", name="published_at")
     */
    protected $publishedAt;
    /**
     * @Assert\DateTime()
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;
    /**
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="posts")
     * @ORM\JoinTable(name="content_categories_attrib")
     */
    protected $categories;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tags;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;
    }
    
    public function setType($type)
    {
        $this->type = $type;
    }
    
    public function getType()
    {
        return $this->type;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {        
        $this->title = $title;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function getPublishedAt()
    {
        return $this->publishedAt;
    }

    public function setPublishedAt($publishedAt)
    {
        $this->publishedAt = $publishedAt;
    }
    
    public function getExcerpt()
    {
        return $this->excerpt;
    }

    public function setExcerpt($excerpt)
    {
        $this->excerpt = $excerpt;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }
    
    public function setLink($link)
    {
        $this->link = $link;
    }
    
    public function getLink()
    {
        return $this->link;
    }
    
    public function setMinilink($minilink)
    {
        $this->minilink = $minilink;
    }
    
    public function getMinilink()
    {
        return $this->minilink;
    }
    
    public function setGithubFile($githubFile)
    {
        $this->githubFile = $githubFile;
    }
    
    public function getGithubFile()
    {
        return $this->githubFile;
    }
    
    public function getGithubFileType()
    {
        $x = explode('.', $this->getGithubFile());
        $extension = end($x);
        
        switch($extension)
        {
            default:        return 'text'; break;
            case 'php':     return 'php'; break;
            case 'html':    return 'html'; break;
            case 'twig':    return 'html'; break;
            case 'yml':     return 'yml'; break;
        }
    }
    
    public function setSocialNetworkId($socialNetworkId)
    {
        $this->socialNetworkId = $socialNetworkId;
    }
    
    public function getSocialNetworkId()
    {
        return $this->socialNetworkId;
    }
    
    public function setPicture($picture)
    {
        $this->picture = $picture;
    }
 
    public function getPicture()
    {
        return $this->picture;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    public function getCategories()
    {
        return $this->categories;
    }
    
    public function getCategoriesList()
    {
        $categories = ''; $i = 1;
        
        foreach ($this->getCategories() as $c)
        {
            if ($i < count($this->getCategories()))
                $categories .= sprintf('%s, ', $c);
            else
                $categories .= $c;
            
            $i++;
        }
        
        return $categories;
    }

    public function setCategories($categories)
    {
        $this->categories = $categories;
    }
    
    public function getTags()
    {
        return $this->tags;
    }

    public function setTags($tags)
    {
        $this->tags = $tags;
    }
    
    public function getTagsCollection()
    {
        return explode(' ', $this->tags);
    }
    
    public function getHashtags()
    {
        $tags = explode(' ', $this->tags);
        $hashtags = '';
        
        foreach ($tags as $t)
            $hashtags .= sprintf('#%s ', $t);
        
        return trim($hashtags);
    }
    
    public function getDisqusId()
    {
        return sprintf('slynett-%s', $this->slug);
    }
    
    public function __toString()
    {
        return $this->title;
    }
    
    public function getFullPicturePath()
    {
        return null === $this->picture ? null : $this->getUploadRootDir(). $this->picture;
    }

    protected function getUploadRootDir()
    {
        return $this->getTmpUploadRootDir().$this->getId()."/";
    }

    protected function getTmpUploadRootDir()
    {
        return __DIR__ . '/../../../../web/uploads/contents/';
    }
    
    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        if (!$this->publishedAt)
            $this->publishedAt = new \DateTime();
        
        if (!$this->updatedAt)
            $this->updatedAt = new \DateTime();
        
        if (!$this->status)
            $this->status = true;
    }
    
    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updatedAt = new \DateTime();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function uploadPicture() {
        if (null === $this->picture)
            return;
        
        if (!$this->id)
            $this->picture->move($this->getTmpUploadRootDir(), $this->picture->getClientOriginalName());
        else
            $this->picture->move($this->getUploadRootDir(), $this->picture->getClientOriginalName());
        
        $this->setPicture($this->picture->getClientOriginalName());
    }
    
    /**
     * @ORM\PostPersist()
     */
    public function movePicture()
    {
        if (null === $this->picture)
            return;
        
        if(!is_dir($this->getUploadRootDir()))
            mkdir($this->getUploadRootDir());

        copy($this->getTmpUploadRootDir().$this->picture, $this->getFullPicturePath());
        unlink($this->getTmpUploadRootDir().$this->picture);
    }

    /**
     * @ORM\PreRemove()
     */
    public function removePicture()
    {
        unlink($this->getFullPicturePath());
        rmdir($this->getUploadRootDir());
    }
    
    public function getDailyMotionPictureUrl()
    {
        return str_replace('/video/', '/thumbnail/video/', $this->link);
    }
    
    public function getDailyMotionEmbedUrl()
    {
        return str_replace('/video/', '/embed/video/', $this->link);
    }
}

src/Sly/ContentBundle/Form/TutorialType.php
<?php

namespace Sly\ContentBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

use Sly\ContentBundle\Entity\Content;

class TutorialType extends AbstractType
{
    public function getDefaultOptions(array $options)
    {
        return array(
            'data_class' => 'Sly\ContentBundle\Entity\Content',
        );
    }
    
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder->add('categories', null)
                ->add('title', 'text')
                ->add('excerpt', 'textarea', array('required' => false))
                ->add('content', 'textarea', array('required' => false))
                ->add('picture')
                ->add('link', 'url', array('required' => false))
                ->add('status', 'checkbox', array('data' => true))
                ->add('publishedAt', 'datetime', array('required' => false, 'widget' => 'single_text'))
        ;
    }

    public function getName()
    {
        return 'content';
    }
}

src/Sly/ContentBundle/Controller/TutorialController.php
<?php

namespace Sly\ContentBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

use Sly\ContentBundle\Entity\Category;
use Sly\ContentBundle\Entity\Content;

class TutorialController extends Controller
{
    public function listAction()
    {
        $em = $this->getDoctrine()->getEntityManager();

        $contentQuery = $em->getRepository('SlyContentBundle:Content')->getContentQ('tutorial');
                
        $contentPaginator = new Pagerfanta(new DoctrineORMAdapter($contentQuery));
        $contentPaginator->setMaxPerPage($this->container->getParameter('sly.content.tutorial.maxperpage'));
        $contentPaginator->setCurrentPage($this->get('request')->query->get('page', 1));
        
        return $this->render('SlyContentBundle:Tutorial:list.html.twig', array(
            'contentPaginator' => $contentPaginator,
        ));
    }
    
    public function categoryListAction(Category $category)
    {
        if (!$category->getStatus()) throw new NotFoundHttpException('This category has been disabled.');
        
        $em = $this->getDoctrine()->getEntityManager();
        
        $contentQuery = $em->getRepository('SlyContentBundle:Content')->getContentByCategoryQ($category, 'tutorial');
        
        $contentPaginator = new Pagerfanta(new DoctrineORMAdapter($contentQuery));
        $contentPaginator->setMaxPerPage($this->container->getParameter('sly.content.tutorial.maxperpage'));
        $contentPaginator->setCurrentPage($this->get('request')->query->get('page', 1));
        
        return $this->render('SlyContentBundle:Tutorial:categoryList.html.twig', array(
            'contentPaginator' => $contentPaginator,
            'category' => $category,
        ));
    }
    
    public function showAction(Request $request, Content $content)
    {
        if (!$content->getStatus()) throw new NotFoundHttpException('This post has been disabled.');
        
        return $this->render('SlyContentBundle:Tutorial:show.html.twig', array(
            'item' => $content,
            'dmplayer' => $this->container->getParameter('sly.content.tutorial.dmplayer'),
        ));
    }
}

src/Sly/ContentBundle/Resources/views/Tutorial/bigItem.html.twig
{% spaceless %}
    <article class="big">
        <h3><a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">{{ item.title }}</a></h3>

        <div>
            <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}" class="overlay"></a>

            <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">
                {%if item.picture %}
                    <img src="{{ '/uploads/contents/%itemId%/%itemPicture%' | replace({'%itemId%': item.id, '%itemPicture%': item.picture}) | apply_filter('medium_b') }}" alt="{{ item }}" />
                {% else %}
                    <img src="{{ '/uploads/tutorial.jpg' | apply_filter('medium_b') }}" alt="{{ item }}" />
                {% endif %}
            </a>

            <ul class="category medium">
                {% for k, cat in item.categories %}
                    <li><a href="{{ path('tutorial_category', {'slug': cat.slug}) }}" class="caticon medium {{ cat.slug }}" title="{{ cat }}"></a></li>
                {% endfor %}
            </ul>
        </div>
        
        <p>
            <abbr title="{{ item.publishedAt | date('core.date.time.big' | trans) }}" class="dtstart">
                {{ 'infos.publishedat' | trans({'%date%': item.publishedAt | date('core.date.time.normal' | trans)}) }}
            </abbr>
        </p>

        <p class="description">
            <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">
                {% if item.excerpt %}
                    {{ item.excerpt | striptags }}
                {% else %}
                    {{ item.content | striptags | truncate(250) }}
                {% endif %}
            </a>
        </p>
        
        {% if item.tags | length %}
            <ul class="tags">
                {% for tag in item.tagsCollection %}
                    <li><a href="#{{ tag }}" class="container">{{ tag }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </article>
{% endspaceless %}

src/Sly/ContentBundle/Resources/views/Tutorial/categoryList.html.twig
{% extends "SlyCoreBundle:Layout:layout.html.twig" %}

{% block title %}{{ category }} | {{ 'seo.title' | trans({}, 'tutorial') }}{% endblock title %}
{% block description %}{{ 'seo.category.description' | trans({'%catName%': category}, 'tutorial') }}{% endblock description %}

{% block content %}
    <h2 role="contentinfo">{{ 'category.title' | trans({'%catName%': category}, 'tutorial') }}</h2>
    
    <nav>{% render 'SlyContentBundle:Component:categories' with {'type': 'tutorial', 'activeCategory': category} %}</nav>

    {% for k, item in contentPaginator %}
        {% include 'SlyContentBundle:Tutorial:mediumItem.html.twig' with {'item': item } %}
    {% else %}
        <p class="empty">{{ 'list.nocontent' | trans({}, 'tutorial') }}</p>
    {% endfor %}
    
    {% if contentPaginator | length %}
        <div class="pager">
            {{ pagerfanta(contentPaginator, 'default') }}
        </div>
    {% endif %}
{% endblock content %}

{% block javascripts %}
    {{ parent() }}
    
    {% render 'SlyContentBundle:Component:disqusCountJS' %}
{% endblock javascripts %}

src/Sly/ContentBundle/Resources/views/Tutorial/item.html.twig
{% from "SlyContentBundle::macro.socialShare.html.twig" import shareBigRButtons %}

<article class="show">
    <header>
        <section role="contentinfo">
            <h2>
                {% if item.categories | length %}                
                    {% for k, cat in item.categories %}
                        <a href="{{ path('tutorial_category', {'slug': cat.slug}) }}" class="category {{ cat.slug }}">{{ cat }}</a>{% if k+1 < item.categories | length %} / {% endif %}
                    {% endfor %}

                    —
                {% endif %}
                
                <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">{{ item }}</a>
            </h2>
        </section>
    </header>
        
    <section class="body">
        <a href="#" class="btn go-share">{{ 'list.item.share' | trans({}, 'tutorial') }}</a>
        
        <iframe frameborder="0" width="{{ dmplayer.width }}" height="{{ dmplayer.height }}" src="{{ item.dailyMotionEmbedUrl }}?width={{ dmplayer.width }}"></iframe>

        <!-- {% if item.tags | length %}
            <ul>
                {% for tag in item.tagsCollection %}
                    <li><a href="#{{ tag }}">{{ tag }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}-->
    </section>
    
    {% include 'SlyCoreBundle:Block/Com/Content:300x250m.html.twig' %}

    {% if item.content %}
        <section class="body">
            <div class="content-show">
                {{ item.content | contentFilters | raw }}
            </div>
            
            <footer>
                <aside class="left author">
                    {% include 'SlyContentBundle:Block:authorPresentation.html.twig' with {'type': 'tutorial'} %}
                </aside>

                <aside class="right">
                    {% include 'SlyContentBundle:Block/Content:socialNetworks.html.twig' with {'type': 'tutorial'} %}
                </aside>
            </footer>
        </section>
    {% endif %}
</article>

src/Sly/ContentBundle/Resources/views/Tutorial/list.html.twig
{% extends "SlyCoreBundle:Layout:layout.html.twig" %}

{% block title %}{{ 'seo.title' | trans({}, 'tutorial') }}{% endblock title %}
{% block description %}{{ 'seo.description' | trans({}, 'tutorial') }}{% endblock description %}

{% block content %}
    {% if app.request.query.get('page') <= 1 %}
        <h2 role="contentinfo">{{ 'list.title' | trans({}, 'tutorial') }}</h2>
    {% endif %}
    
    <nav>{% render 'SlyContentBundle:Component:categories' with {'type': 'tutorial'} %}</nav>

    {% for k, item in contentPaginator %}
        {% include 'SlyContentBundle:Tutorial:mediumItem.html.twig' with {'item': item } %}
    {% else %}
        <p class="empty">{{ 'list.nocontent' | trans({}, 'tutorial') }}</p>
    {% endfor %}
    
    {% if contentPaginator | length %}
        <div class="pager">
            {{ pagerfanta(contentPaginator, 'default') }}
        </div>
    {% endif %}
{% endblock content %}

{% block javascripts %}
    {{ parent() }}
    
    {% render 'SlyContentBundle:Component:disqusCountJS' %}
{% endblock javascripts %}

src/Sly/ContentBundle/Resources/views/Tutorial/list.xml.twig
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
        <title>{{ 'seo.title' | trans({}, 'tutorial') }} | {{ project.name }}</title>
        <description>{{ 'seo.description' | trans({}, 'tutorial') }}</description>
        <link>{{ url('tutorial') }}</link>
        <lastBuildDate>{{ now | date('D, d M Y H:i:s') }}</lastBuildDate>
        <pubDate>{{ now | date('D, d M Y H:i:s') }}</pubDate>
        
        {% for item in contentPaginator %}
            <item>
                <title>{{ item }}</title>
                <description>{{ item.excerpt | striptags }}</description>
                <link>{{ url('tutorial_show', {'slug': item.slug }) }}</link>
                <guid>{{ item.id }}-{{ item.slug }}</guid>
                <pubDate>{{ item.publishedAt | date('D, d M Y H:i:s') }}</pubDate>
            </item>
        {% endfor %}
</channel>
</rss>

src/Sly/ContentBundle/Resources/views/Tutorial/mediumItem.html.twig
{% spaceless %}
    <article class="tutorial">
        {%if item.picture %}
            <img src="{{ '/uploads/contents/%itemId%/%itemPicture%' | replace({'%itemId%': item.id, '%itemPicture%': item.picture}) | apply_filter('tutorial') }}" alt="{{ item }}" />
        {% else %}
            <img src="{{ '/uploads/labs.jpg' | apply_filter('tutorial') }}" alt="{{ item }}" />
        {% endif %}
        
        <div class="mask">
            <h3><a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">{{ item.title }}</a></h3>
            <p>
                <span>
                    {% if item.categories | length %}
                        {% for k, cat in item.categories %}
                            <a href="{{ path('tutorial_category', {'slug': cat.slug}) }}" class="category {{ cat.slug }}">{{ cat }}</a>{% if k+1 < item.categories | length %} / {% endif %}
                        {% endfor %}

                        —
                    {% endif %}
                </span>
                
                <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}">
                    A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.
                </a>
            </p>
            <a href="{{ path('tutorial_show', {'slug': item.slug }) }}" title="{{ item }}" class="info">
                {{ 'list.show' | trans({}, 'tutorial') }}
            </a>
        </div>
    </article>
{% endspaceless %}

src/Sly/ContentBundle/Resources/views/Tutorial/rightSidebarItem.html.twig
<section>
    <h3>{{ 'sidebar.categories.title' | trans }}</h3>
    
    <div class="content">
        <nav>{% render 'SlyContentBundle:Component:categories' with {'type': 'blog', 'noActiveCategory': true} %}</nav>
    </div>
</section>

{% include 'SlyContentBundle:Block:tabSkel2.html.twig' with {'type': 'blog'} %}

src/Sly/ContentBundle/Resources/views/Tutorial/show.html.twig
{% extends "SlyCoreBundle:Layout:layout.rightSidebar.html.twig" %}

{% block title %}{{ item }} | {{ 'seo.title' | trans({}, 'tutorial') }}{% endblock title %}
{% block description %}{{ item.excerpt | striptags }}{% endblock description %}

{% block rightSidebar %}
    {% include 'SlyContentBundle:Tutorial:rightSidebarItem.html.twig' %}
{% endblock rightSidebar %}

{% block content %}
    {% include 'SlyContentBundle:Tutorial:item.html.twig' with {'item': item } %}
    
    <h2>{{ 'list.item.related' | trans({}, 'tutorial') }}</h2>
    
    <aside class="related">
        {% render 'SlyContentBundle:Component:lastItems' with {
            'type': 'tutorial',
            'categories': item.categories,
            'withoutItem': item,
            'withPicture': true,
            'count': 3
        } %}
    </aside>
    
    <aside class="comments">
        <h2><a href="#disqus_thread" data-disqus-identifier="{{ item.disqusId }}">&nbsp;</a></h2>
        
        <div id="disqus_thread"></div>
    </aside>
{% endblock content %}

{% block javascripts %}
    {{ parent() }}
    
    {% render 'SlyContentBundle:Component:disqusCountJS' %}
    {% render 'SlyContentBundle:Component:disqusJS' with {'item': item, 'type': 'tutorial'} %}
{% endblock javascripts %}